import type { Aula } from "../../../types";

// Cópia estrutural do documento canônico; não editar o conteúdo editorial aqui.
export default {
  "id": "DTRAB-005",
  "titulo": "DTRAB-005 — Salário e remuneração: conceitos, parcelas salariais, utilidades, gorjetas, gratificações, prêmios, diárias, descontos, proteção salarial e equiparação salarial — fundamentos",
  "materiaId": "direito-trabalho",
  "cargoIds": [
    "trt2_aj_adm",
    "trt2_tj_adm",
    "trt15_aj_adm",
    "trt15_tj_adm"
  ],
  "editalRefs": [
    "TRT-2 — Edital nº 01/2025 — Analista Judiciário – Área Administrativa — salário mínimo",
    "salário e remuneração",
    "composição",
    "modalidades",
    "formas e meios de pagamento",
    "adicionais",
    "gorjetas",
    "13º salário",
    "equiparação salarial, requisitos, excludentes, igualdade salarial, desvio e acúmulo de função",
    "TRT-2 — Edital nº 01/2025 — Técnico Judiciário – Área Administrativa — salário mínimo",
    "salário e remuneração",
    "composição",
    "formas e meios de pagamento",
    "modalidades",
    "adicionais",
    "13º salário",
    "equiparação salarial",
    "TRT-15 — Edital nº 01/2024 — Analista Judiciário – Área Administrativa — salário mínimo",
    "salário e remuneração",
    "composição",
    "modalidades",
    "formas e meios de pagamento",
    "adicionais",
    "gorjetas",
    "13º salário",
    "equiparação salarial, requisitos, excludentes, igualdade salarial, desvio e acúmulo de função",
    "TRT-15 — Edital nº 01/2024 — Técnico Judiciário – Área Administrativa — salário mínimo",
    "salário e remuneração",
    "composição",
    "pagamento",
    "modalidades",
    "adicionais",
    "13º salário",
    "equiparação salarial."
  ],
  "sourceRefs": [
    "Constituição Federal — art. 7º, IV a XI",
    "CLT — Decreto-Lei nº 5.452/1943 — texto compilado oficial vigente — arts. 76, 78 e 457 a 466",
    "Lei nº 4.090/1962",
    "Lei nº 4.749/1965",
    "Lei nº 14.611/2023",
    "TRT-2 — Edital nº 01/2025",
    "TRT-15 — Edital nº 01/2024",
    "DTRAB-001",
    "DTRAB-002",
    "DTRAB-003",
    "DTRAB-004",
    "CHECKPOINT — Produção intercalada de matérias."
  ],
  "status": "em_producao",
  "topicoId": "DTRAB-005",
  "tipo": "oficial",
  "demonstracao": false,
  "secoes": [],
  "extensoes": [],
  "documentoArquivo": "direito-trabalho/DTRAB-005.json",
  "materiaEditorial": "Direito do Trabalho",
  "classificacaoEditorial": "núcleo trabalhista consolidado — salário, remuneração, parcelas, proteção salarial e equiparação",
  "documentoUrl": "https://docs.google.com/document/d/1WSJR3kDXc7V_WYpM6qEjyHwAgGP-PHx-sCbEGgH9A8c/edit?usp=drivesdk"
} satisfies Aula;
